name: CI/CD Docker → EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Docker Buildx (needed for docker/build-push-action)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4️⃣ Build and push Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: pratap9/dynamodb_ecr_cicd:latest

      # 5️⃣ SSH into EC2 and deploy
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Pull the latest Docker image
            docker pull pratap9/dynamodb_ecr_cicd:latest

            # Stop and remove old container if running
            if [ $(docker ps -q -f name=node-app) ]; then
              docker stop node-app
              docker rm node-app
            fi

            # Run the new container
            docker run -d --name node-app -p 3000:3000 pratap9/dynamodb_ecr_cicd:latest

            # Optional: clean up dangling images to save space
            docker image prune -f
